### ISSUE TITLE
search-words logic runtime error

### ISSUE THREAD

**Issue by maguro923** [GodaHaruki/study-english-words-app#26]
When I use big-size words.csv and use search box, happen this error
![IMG_1386](https://github.com/user-attachments/assets/01c1adec-fc9f-4c1e-9427-27c48c57ce94)
I don't know this logic in detail,but I think this problem is caused by to use a recursive function or too big file size.

**Comment by GodaHaruki** [comment]
I think this problem is caused by your Unstandard CSV because I tried calling this hook with a 10,000 line CSV and it did not throw an error.
https://github.com/GodaHaruki/study-english-words-app/blob/16a177c8864e13d1b689c087e3194324ba02dad8/hooks/search-word/hooks.ts#L4-L7
